seed_everything: 11
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: stock-tweets
        log_model: false
  max_epochs: 15
  log_every_n_steps: 1
  gpus: 1
model:
  optim: AdamW
  lr: 0.00001
  transformer_config: 
    class_path: src.model.transformer.BertBaseMultilingualUncasedSentiment
  freeze_transformer: False
  hidden_dim: 64
  attention_input: both # followers # sentiment
  tweet_max_len: 60 # 100 # TODO revisit
  test_as_second_val_loader: true
data:
  batch_size: 1
  classify_threshold_down: -0.005
  classify_threshold_up: +0.007 # +0.0055
  min_followers: 0 # 100  # TODO try multiple values
  min_tweets_day: 5
  more_recent_first: true
  time_lag: 0
  max_lag: ~
  tweet_path: data/tweet/raw
  price_path: data/price/preprocessed
  num_workers: 5
  data_split: 
    train:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2014-01-01
        end: 2015-08-01
    val:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2015-08-01
        end: 2015-10-01
    test:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2015-10-01
        end: 2016-01-01
