seed_everything: 11
trainer:
  logger:
    - class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: stock-tweets
        log_model: false
  max_epochs: 50
  log_every_n_steps: 1
  gpus: 1
model:
  optim: AdamW
  lr: 0.00001
  transformer_config: 
    class_path: src.model.transformer.BertBaseMultilingualUncasedSentiment
  freeze_transformer: False
  hidden_dim: 64
  classify_threshold_down: &thres_down -0.005
  classify_threshold_up: &thres_up +0.007 # +0.0055
  tweet_max_len: 512
data:
  batch_size: 8 
  classify_threshold_down: *thres_down
  classify_threshold_up: *thres_up
  min_followers: 0  # should be 0 for comparison, doesn't seem to have a big effect
  min_tweets_day: 0 # should be 0 for comparison, makes training easier (likely because less data)
  time_lag: 1
  tweet_path: data/tweet/raw
  price_path: data/price/preprocessed
  num_workers: 5
  data_split: 
    train:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2014-01-01
        end: 2015-08-01
    val:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2015-08-01
        end: 2015-10-01
    test:
      class_path: src.util.splits.DateRange
      init_args:
        start: 2015-10-01
        end: 2016-01-01
